# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 13:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Stack Name')),
                ('backend', models.CharField(choices=[('aws', 'AWS'), ('os', 'OpenStack')], max_length=1, verbose_name='Backend')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stacks', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
        ),
    ]
