# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 21:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('identity', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Stack Name')),
                ('backend', models.CharField(choices=[('aws', 'AWS'), ('os', 'OpenStack')], max_length=1, verbose_name='Backend')),
                ('status', models.CharField(choices=[('success', 'Success'), ('fail', 'Fail'), ('unknown', 'Unknown')], max_length=1, verbose_name='Status')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stacks', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stacks', to='identity.Tenant', verbose_name='Tenant')),
            ],
        ),
    ]
