# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0002_stack_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='stack',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('fail', 'Fail'), ('unknown', 'Unknown')], default='ok', max_length=1, verbose_name='Status'),
            preserve_default=False,
        ),
    ]
